using MailKit.Net.Smtp;
using MailKit.Security;
using Microsoft.Extensions.Configuration;
using MimeKit;

namespace TaskAppService
{
    public class EmailService
    {
        private readonly IConfiguration _configuration;

        public EmailService(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public void SendTaskNotification(string recipientEmail, string taskName, string action)
        {
            string fromName = _configuration["EmailSettings:FromName"] ?? "Task App System";
            string fromEmail = _configuration["EmailSettings:FromEmail"] ?? "notifications@taskapp.com";
            string smtpHost = _configuration["EmailSettings:SmtpHost"] ?? "sandbox.smtp.mailtrap.io";
            int smtpPort = int.TryParse(_configuration["EmailSettings:SmtpPort"], out int port) ? port : 2525;
            string username = _configuration["EmailSettings:Username"] ?? string.Empty;
            string password = _configuration["EmailSettings:Password"] ?? string.Empty;

            var message = new MimeMessage();
            message.From.Add(new MailboxAddress(fromName, fromEmail));
            message.To.Add(new MailboxAddress("Task User", recipientEmail));
            message.Subject = $"Task Status Alert: {action}";
            message.Body = new TextPart("plain")
            {
                Text = $"Task Update Notification\n\n" +
                       $"Task Name: \"{taskName}\"\n" +
                       $"Action: {action}\n\n" +
                       $"This email was generated by your TaskApp System."
            };

            using (var client = new SmtpClient())
            {
                client.Connect(smtpHost, smtpPort, SecureSocketOptions.StartTls);
                if (!string.IsNullOrEmpty(username) && !string.IsNullOrEmpty(password))
                {
                    client.Authenticate(username, password);
                }
                client.Send(message);
                client.Disconnect(true);
            }
        }

        public void SendTaskNotification(string taskName, string action)
        {
            string recipient = _configuration["EmailSettings:RecipientEmail"] ?? "testuser@example.com";
            SendTaskNotification(recipient, taskName, action);
        }

        public void SendSimpleNotification(string recipientEmail, string messageText, string subject = "Task Notification")
        {
            string fromName = _configuration["EmailSettings:FromName"] ?? "Task App System";
            string fromEmail = _configuration["EmailSettings:FromEmail"] ?? "notifications@taskapp.com";
            string smtpHost = _configuration["EmailSettings:SmtpHost"] ?? "sandbox.smtp.mailtrap.io";
            int smtpPort = int.TryParse(_configuration["EmailSettings:SmtpPort"], out int port) ? port : 2525;
            string username = _configuration["EmailSettings:Username"] ?? string.Empty;
            string password = _configuration["EmailSettings:Password"] ?? string.Empty;

            var message = new MimeMessage();
            message.From.Add(new MailboxAddress(fromName, fromEmail));
            message.To.Add(new MailboxAddress("Task User", recipientEmail));
            message.Subject = subject;
            message.Body = new TextPart("plain")
            {
                Text = messageText
            };

            using (var client = new SmtpClient())
            {
                client.Connect(smtpHost, smtpPort, SecureSocketOptions.StartTls);
                if (!string.IsNullOrEmpty(username) && !string.IsNullOrEmpty(password))
                {
                    client.Authenticate(username, password);
                }
                client.Send(message);
                client.Disconnect(true);
            }
        }
    }
}